# Random Sampling

In [1]:
import numpy as np

In [3]:
np.__version__

'1.11.2'

In [5]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [9]:
resArray = np.random.uniform(0, 1, (3, 2))
print(resArray)

[[0.5991794  0.00915874]
 [0.76432705 0.39819123]
 [0.47534634 0.28018092]]


Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [5]:
resArray = np.random.normal(0, 1, (1000, 1000))
#verify the means
print(np.mean(resArray))
#verify the standard distribution
print(np.std(resArray))

0.0014760467963285662
0.9990745913386525


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [43]:
resArray = np.random.uniform(0, 3.5, (3, 2))
resArray = resArray.astype(int)
print(resArray)

[[1 2]
 [1 0]
 [0 2]]


Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [48]:
x = ['3 out of 10', '5 out of 10', '2 out of 10']
for index in range(10):
    res = np.random.choice(x, p=[0.3, 0.5, 0.2])
    print(res)


5 out of 10
2 out of 10
5 out of 10
5 out of 10
2 out of 10
2 out of 10
3 out of 10
5 out of 10
3 out of 10
2 out of 10


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [50]:
resArray = np.random.choice(10, 3, replace=False)
print(resArray)

[7 6 8]


## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [59]:
newArray = np.arange(10)
np.random.shuffle(newArray)
print(newArray)

[8 9 7 1 0 3 6 2 5 4]


In [63]:
# Or
resArray = np.random.permutation(10)
print(resArray)


[0 7 1 3 9 4 2 5 6 8]


## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [67]:
np.random.seed(10)
for index in range(10):
    print(np.random.choice(np.arange(1, 10), 3))

[5 1 2]
[1 2 9]
[1 9 7]
[5 4 1]
[5 7 9]
[2 9 5]
[2 4 7]
[6 4 7]
[2 5 3]
[7 8 9]
