# Soring, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

In [3]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [2]:
x = np.array([[1,4],[3,1]])
np.sort(x, axis=1)


array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [13]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
np.lexsort((first_names, surnames))


[1 2 0]


Q3. Get the indices that would sort x along the second axis.

In [4]:
x = np.array([[1,4],[3,1]])
res = np.argsort(x, axis=1)
print(res)

[[0 1]
 [1 0]]


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [18]:
x = np.random.permutation(10)
print ("x =", x) 
newArray = np.partition(x, 5)
print("The new array is: ", newArray)

x = [4 8 7 1 3 5 6 2 0 9]
The new array is:  [2 3 0 1 4 5 6 7 8 9]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [21]:
x = np.random.permutation(10)
print("x =", x)
Parti_arr = np.partition(x, 5)
print("Partitioned = ", Parti_arr)
indices = np.argpartition(x, 5)
print("Indices = ", indices)


x = [9 1 7 0 4 5 6 2 8 3]
Partitioned =  [1 3 2 0 4 5 6 7 8 9]
Indices =  [1 9 7 3 4 5 6 2 8 0]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [23]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)
print("maximum values: ", np.max(x, axis=1))
print("maximum indices: ",np.argmax(x, axis=1))
print("ninimum values: ", np.min(x, axis=1))
print("maximum indices: ",np.argmin(x, axis=1))


x = [[6 0 7 8 1]
 [5 3 9 2 4]]
maximum values:  [8 9]
maximum indices:  [3 2]
ninimum values:  [0 2]
maximum indices:  [1 3]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [25]:
x = np.array([[np.nan, 4], [3, 2]])
print("The minimum values: ", np.nanmin(x, axis=1))
print("min indices: ", np.nanargmin(x, axis=1))
print("The maximum values: ", np.nanmax(x, axis=1))
print("max indices: ", np.nanargmax(x, axis=1))

The minimum values:  [4. 2.]
min indices:  [1 1]
The maximum values:  [4. 3.]
max indices:  [1 0]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [26]:
x = np.array([[1, 2, 3], [1, 3, 5]])
pos = np.argwhere(x > 2)
print(pos)

[[0 2]
 [1 1]
 [1 2]]


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [27]:
x = np.array([[1, 2, 3], [1, 3, 5]])
res = np.flatnonzero(x > 2)
print(res)

[2 4 5]


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [40]:
x = np.arange(-5, 4).reshape(3, 3)
clipped_array = np.where(x < 0, 0, x)
print(clipped_array)


[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [41]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
res = np.searchsorted(x, y)
print(res)

[0 2 1 3]


## Counting

Q12. Get the number of nonzero elements in x.

In [42]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
res = np.count_nonzero(x)
print(res)


5


In [44]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
res = np.flatnonzero(x).size
print(res)

5
