<a href="https://colab.research.google.com/github/ThanhLe86/numpy_exercises/blob/master/1_Array_creation_routines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array creation routines

## Ones and zeros

In [2]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

In [88]:
arr = np.empty([2, 2], dtype=int)
print(arr)

[[1 1]
 [1 1]]


Let X = np.array([1,2,3], [4,5,6], np.int32).
Create a new array with the same shape and type as X.

In [93]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
newX = np.empty_like(X)
print(X, "\n")
print(newX, "\n")
print("The shape of X: ", X.shape)
print("The shape of newX: ", newX.shape)
print("The type of X: ", X.dtype)
print("The type of newX: ", newX.dtype)

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]] 

The shape of X:  (2, 3)
The shape of newX:  (2, 3)
The type of X:  int32
The type of newX:  int32


Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [95]:
newArray = np.eye(3, dtype=int)
print(newArray)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Create a new array of 3*2 float numbers, filled with ones.

In [96]:
newArray = np.ones((3,2), dtype=float)
print(newArray)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [98]:
x = np.arange(4, dtype=np.int64)
newX = np.ones_like(x)
print(x)
print(newX)

[0 1 2 3]
[1 1 1 1]


Create a new array of 3*2 float numbers, filled with zeros.

In [99]:
newArray = np.zeros((3,2), dtype = float)
print(newArray)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [101]:
x = np.arange(4, dtype=np.int64)
newX = np.zeros_like(x)
print(x)
print(newX)

[0 1 2 3]
[0 0 0 0]


Create a new array of 2*5 uints, filled with 6.

In [102]:
newArray = np.full((2,5), 6, dtype = np.uint32)
print(newArray)
print(newArray.dtype)

[[6 6 6 6 6]
 [6 6 6 6 6]]
uint32


Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [104]:
x = np.arange(4, dtype=np.int64)
newX = np.full_like(x, 6)
print(x)
print(newX)

[0 1 2 3]
[6 6 6 6]


## From existing data

Create an array of [1, 2, 3].

In [105]:
newArray = np.array([1, 2, 3])
print(newArray)

[1 2 3]


Let x = [1, 2]. Convert it into an array.

In [106]:
x = [1,2]
newX = np.asarray(x)
print(newX)

[1 2]


Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [107]:
X = np.array([[1, 2], [3, 4]])
newX = np.asmatrix(X)
print(newX)

[[1 2]
 [3 4]]


Let x = [1, 2]. Conver it into an array of `float`.

In [108]:
x = [1, 2]
newx = np.asarray(x, dtype=float)
print(newx)


[1. 2.]


Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [109]:
x = np.array([30])
X_scalar = x.item()
print(X_scalar)

30


Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [115]:
x = np.array([1, 2, 3])
newX = np.copy(x)
print("x: ", x)
print("newX: ", newX)
print("id of x: ", id(x))
print("id of newX: ", id(newX))


x:  [1 2 3]
newX:  [1 2 3]
id of x:  134391588237552
id of newX:  134391588214160


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

In [119]:
iterator = (x * 2 for x in range(1, 51))
evenArray = np.fromiter(iterator, int)
print(evenArray)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [122]:
newArray = np.arange(3, 10, 7/50)
print(newArray)
print(len(newArray))


[3.   3.14 3.28 3.42 3.56 3.7  3.84 3.98 4.12 4.26 4.4  4.54 4.68 4.82
 4.96 5.1  5.24 5.38 5.52 5.66 5.8  5.94 6.08 6.22 6.36 6.5  6.64 6.78
 6.92 7.06 7.2  7.34 7.48 7.62 7.76 7.9  8.04 8.18 8.32 8.46 8.6  8.74
 8.88 9.02 9.16 9.3  9.44 9.58 9.72 9.86]
50


Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

In [124]:
newArray = np.logspace(3, 10, 50, endpoint=False)
print(newArray)

[1.00000000e+03 1.38038426e+03 1.90546072e+03 2.63026799e+03
 3.63078055e+03 5.01187234e+03 6.91830971e+03 9.54992586e+03
 1.31825674e+04 1.81970086e+04 2.51188643e+04 3.46736850e+04
 4.78630092e+04 6.60693448e+04 9.12010839e+04 1.25892541e+05
 1.73780083e+05 2.39883292e+05 3.31131121e+05 4.57088190e+05
 6.30957344e+05 8.70963590e+05 1.20226443e+06 1.65958691e+06
 2.29086765e+06 3.16227766e+06 4.36515832e+06 6.02559586e+06
 8.31763771e+06 1.14815362e+07 1.58489319e+07 2.18776162e+07
 3.01995172e+07 4.16869383e+07 5.75439937e+07 7.94328235e+07
 1.09647820e+08 1.51356125e+08 2.08929613e+08 2.88403150e+08
 3.98107171e+08 5.49540874e+08 7.58577575e+08 1.04712855e+09
 1.44543977e+09 1.99526231e+09 2.75422870e+09 3.80189396e+09
 5.24807460e+09 7.24435960e+09]


## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [ ]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])


array([ 0,  5, 10])

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

Create an array which looks like below.
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])